playkit/src/main/java/com/kaltura/playkit/PlayerEvent.java
playkit/src/main/java/com/kaltura/playkit/player/AudioTrack.java
playkit/src/main/java/com/kaltura/playkit/player/BaseTrack.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/PKTracks.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerEngine.java
playkit/src/main/java/com/kaltura/playkit/player/TextTrack.java
playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java
playkit/src/main/java/com/kaltura/playkit/player/VideoTrack.java
playkit/src/main/java/com/kaltura/playkit/utils/Consts.java
playkitdemo/src/main/java/com/kaltura/playkitdemo/MainActivity.java

- added support for disabling text tracks.

tracks moved to the same package with player.

---

playkit/src/main/java/com/kaltura/playkit/PKMediaFormat.java
playkit/src/main/java/com/kaltura/playkit/backend/ovp/PlaySourceUrlBuilder.java

replace & with ? in query params

remove extra “.” from extension

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/AdCuePoints.java

public List<Long> getAdCuePoints() {
return adCuePoints;
}

add getter getAdCuePoints

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java

so we have to destroy and load again

VE-86 Fix trigger distributor event in IMA not called in changemedia

---

playkit/src/main/java/com/kaltura/playkit/backend/ovp/KalturaOvpMediaProvider.java
playkit/src/main/java/com/kaltura/playkit/backend/ovp/services/BaseEntryService.java

fix the server name for wvc to widevine.WIDEVINE

fix wvc request format - tags=‘all’

---

playkit/src/main/java/com/kaltura/playkit/MessageBus.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java

Message bus now will post events in thread safe way.

Set start position only for new entrys

---

playkit/src/androidTest/java/com/kaltura/playkit/player/SourceSelectorAndroidTest.java
playkit/src/main/java/com/kaltura/playkit/PKMediaFormat.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/SourceSelector.java

This includes source selector and playback, but not media provider.

Support mp3 files

---

playkit/src/main/java/com/kaltura/playkit/plugins/PhoenixAnalyticsPlugin.java

media config not needed in load of plugin

prevent null exception

---

playkit/src/main/java/com/kaltura/playkit/ads/AdEnabledPlayerController.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/AdsProvider.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java

in change media while ad playing we will stop IMA as well

support stop in IMA decorator

---

playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/plugins/PhoenixAnalyticsPlugin.java

fix isFirst play flag to be true incase onUpdate media called

make sure window is not null in init Exo

---

playkit/src/androidTest/java/com/kaltura/playkit/plugins/MockPlayer.java
playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/PKMediaSourceConfig.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java

Added flag that indicates if application is interested in receiving cea-608 text track within trackInfo object.

Enable CEA-608 flag

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java

so we register only once for each player/messagebus instance

in case change media is done register to event will happen again

---

playkit/src/main/java/com/kaltura/playkit/plugins/Youbora/YouboraPlugin.java

do not call adPlugin methods in Youbora plugin in case it is not configured in the plugin

FEM-917_1                  

---

playkit/src/main/java/com/kaltura/playkit/plugins/PhoenixAnalyticsPlugin.java

If finished was triggered do not send Play/Pause events.

FEM-1382_1

---

playkit/src/main/java/com/kaltura/playkit/ads/PKAdInfo.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/AdInfo.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java

add more details in AdInfo
int      getTotalAdsInPod();
int      getAdIndexInPod();
int      getPodCount();
int      getPodIndex();
boolean  isBumper();

IMA create adLoader only once in Plugin lifetime

---

playkit/src/main/java/com/kaltura/playkit/plugins/youbora/YouboraLibraryManager.java

quick casting fix

---

playkit/src/main/java/com/kaltura/playkit/Utils.java

Please add a detailed description of the change, weather it's an enhancement or a bugfix.

Add return empty string

---

playkit/src/main/java/com/kaltura/playkit/PKDeviceCapabilities.java

Also added detection if PlayReady is supported.

Fix a potential crash in PKDeviceCapabilities

---

playkit/src/main/java/com/kaltura/playkit/PKDeviceCapabilities.java

- Add system info to error report
- Remove redundant conversion from JSONObject to Gson's JsonObject.

Device capabilities error report

---

build.gradle
playkit/build.gradle
playkit/version.gradle

Please add a detailed description of the change, weather it's an enhancement or a bugfix.

pom-fix revert

---

playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java

changed the way we assign lastTrackSelectionIds to requestedTrackSelectionIds. instread of = use System.copyArray()

Small bug fix.

---

playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java

Fem 1206_1

---

playkit/src/main/java/com/kaltura/playkit/PKTrackConfig.java

add support in Legacy language codes
for auto pre defined track language

handle deprecated languages in locale

---

playkit/build.gradle

Please add a detailed description of the change, whether it's an enhancement or a bugfix.

netikt api to compile

---

build.gradle
playkit/build.gradle

Please add a detailed description of the change, whether it's an enhancement or a bugfix.

fix jitpack

---

playkit/build.gradle

Please add a detailed description of the change, whether it's an enhancement or a bugfix.

move to compile

---

playkit/src/main/java/com/kaltura/playkit/mediaproviders/MediaProvidersUtils.java
playkit/src/main/java/com/kaltura/playkit/mediaproviders/ott/PhoenixMediaProvider.java
playkit/src/main/java/com/kaltura/playkit/mediaproviders/ovp/KalturaOvpMediaProvider.java

filter out Fair Play from returned sources given by providers

FEM-1818 filter out FairPlay from Android providers getPlaybackContext sources

---

docs/MediaConfig.md
docs/PlayerSettings.md
playkit/src/main/java/com/kaltura/playkit/PKMediaConfig.java
playkit/src/main/java/com/kaltura/playkit/PKTrackConfig.java
playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/mediaproviders/ott/PhoenixMediaProvider.java
playkit/src/main/java/com/kaltura/playkit/mediaproviders/ovp/KalturaOvpMediaProvider.java
playkit/src/main/java/com/kaltura/playkit/player/PKMediaSourceConfig.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java

Captions: no captions displayed ,if selectionMode=AUTO and no default configured for an entry

FEM-1838 + Moving preferred audio/text track from mediaConfig to player settings

---

playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java

Track Selection helper
before calling trackSelection.getSelectedFormat

Add NPE protection

---

playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/PKMediaSourceConfig.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerSetting.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerSettings.java

refactor Settings creation
add ability to ask ExoPlayer to allowCrossProtocol redirect  if 
player.getSettings().setAllowCrossProtocolRedirect(true) is set

FEM-1953 Add setAllowCrossProtocolRedirect to settings

---

playkit/src/main/java/com/kaltura/playkit/ads/AdEnabledPlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerView.java
playkit/src/main/java/com/kaltura/playkit/player/MediaPlayerView.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerView.java

revert using enable/disable surface in IMAPlugin

revert using enable/disable surface in IMAPlugin

---

playkit/src/main/java/com/kaltura/playkit/api/base/model/BasePlaybackContext.java

instead No source  found is sent which is not correct

FEM-2023 No AccesssControl Blocked Error is sent in OVPMedia Provider

---

playkit/src/main/java/com/kaltura/playkit/api/base/model/BasePlaybackContext.java

In case OvpMediaProvider has Blocked Rule without Message 
create an BlockedError and not send No sources found Error

FEM-2023 - send AccessControl Blocked Error if the getPlaybackContext has no message in 

---

playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerView.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java

In case ima fails to play is player != null and ad is not playing call player play

FEM-2031 player is not auto play after back from BG if ad was not served

---

playkit/build.gradle

Fixes  ExpandedController crash when audio selection during cast incase stream is mutli audio but not multi text

upgrade plays services to 15.0.0 

---

playkit/build.gradle
playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/player/CustomHttpDataSourceFactory.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerView.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerSettings.java
playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java
playkit/src/main/java/com/kaltura/playkit/utils/EventLogger.java

+ Upgrade Exoplayer version to 2.7.0
+ Major refactor on the ExoPlayerView.java
+ Add setSecureSurface api to Settings.
+ Small cleanup in CustomHttpDataSourceFactory. We don`t use TransferListener<? super DataSource> so set it to null by default

+ Upgrade Exoplayer to 2.7.0

---

playkit/src/main/java/com/kaltura/playkit/plugins/ovp/KalturaStatsPlugin.java

- Fix is for 'currentPoint'. Value will be sent in seconds now.
- 'duration' not changed. It was already in seconds.

- FEM-2049 fixed.(Develop Branch)

---

playkit/build.gradle
playkit/src/main/java/com/kaltura/playkit/ads/AdEvent.java

add ad buffer event
change exo compilation to api needed for IMAExoPlugin

add ad buffer event

---

playkit/src/androidTest/java/com/kaltura/playkit/plugins/MockPlayer.java
playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/PlayerDecoratorBase.java
playkit/src/main/java/com/kaltura/playkit/PlayerEvent.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/MediaPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerEngine.java
playkit/src/main/java/com/kaltura/playkit/utils/Consts.java
playkitdemo/src/main/java/com/kaltura/playkitdemo/MainActivity.java

Add api support for changing player speed -> 
player.setPlaybackRate(rate) 
player.getPlaybackRate()

FEM-918 - Add api support for changing player speed

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/ExoPlayerWithAdPlayback.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAExoPlugin.java

IMAExoPlugin:
Do not call pause if player is not playing
Do not call playCallback twice

FEM-2109 IMAExoPlayer Ads are missed in HLS/DASH ads in skip

---

playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerSettings.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAExoPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java
playkitdemo/src/main/java/com/kaltura/playkitdemo/MainActivity.java

- If Ad autoplay is true: Coming from background to foreground, Ad will play.
- If Ad autoplay is false: Coming from background to foreground, Ad will not play.

- FEM-2064 : Ad autoplay functionality for IMAExoPlugin & IMAPlugin

---

playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java

+ Assure that PlayerController.java adds PlayerView to view hierarchy at the init stage only for PlayerEngineType.MediaPlayer

FEM-2014_1

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/ExoPlayerWithAdPlayback.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAExoPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java
playkitdemo/build.gradle
playkitdemo/src/main/java/com/kaltura/playkitdemo/MainActivity.java
settings.gradle

Add timer to prepare and start playback if Ad Request callback is not received

FEM-2126 ad request timeout so playback will start if IMA stuck

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/ExoPlayerWithAdPlayback.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAExoPlugin.java
playkitdemo/src/main/java/com/kaltura/playkitdemo/MainActivity.java

FEM-2133 : Player Error is being fired from Ad Player to IMAExoPlugin

- FEM-2133 : Player Error should be fired from Ad Player to IMAExoPlugin so App can get it also

---

playkit/src/main/java/com/kaltura/playkit/PKMediaEntry.java
playkit/src/main/java/com/kaltura/playkit/PKPlugin.java
playkit/src/main/java/com/kaltura/playkit/PKPluginConfigs.java
playkit/src/main/java/com/kaltura/playkit/api/ovp/model/KalturaMediaEntry.java
playkit/src/main/java/com/kaltura/playkit/api/ovp/services/BaseEntryService.java
playkit/src/main/java/com/kaltura/playkit/api/phoenix/model/KalturaMediaAsset.java
playkit/src/main/java/com/kaltura/playkit/api/phoenix/model/KalturaThumbnail.java
playkit/src/main/java/com/kaltura/playkit/api/phoenix/model/MetaObject.java
playkit/src/main/java/com/kaltura/playkit/mediaproviders/MediaProvidersUtils.java
playkit/src/main/java/com/kaltura/playkit/mediaproviders/ott/PhoenixMediaProvider.java
playkit/src/main/java/com/kaltura/playkit/mediaproviders/ovp/KalturaOvpMediaProvider.java
playkit/src/main/java/com/kaltura/playkit/plugins/ott/PhoenixAnalyticsConfig.java
playkit/src/main/java/com/kaltura/playkit/plugins/ott/PhoenixAnalyticsPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ovp/KalturaLiveStatsConfig.java
playkit/src/main/java/com/kaltura/playkit/plugins/ovp/KalturaLiveStatsPlugin.java

OTT provider:
+ Sdd support for 360/vr entries.
+ Added values that obtained from response and placed into PKMediaEntry.Metadata Map(description, thumbnailUrl e.t.c)
+ Added KalturaThumbnail object.
+ Added Meta object
OVP provider:
+ Added values that obtained from response and placed into PKMediaEntry.Metadata Map(description, thumbnailUrl e.t.c)

Fem 1749 1

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/AdEvent.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/ExoPlayerWithAdPlayback.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAExoPlugin.java
playkitdemo/src/main/java/com/kaltura/playkitdemo/MainActivity.java

- Send AD_FIRST_PLAY event once IMAExoPlugin starts playback

- FEM-2119: Send AD_FIRST_PLAY event once IMAExoPlugin starts Ad playback

---

playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAConfig.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAExoPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ads/ima/IMAPlugin.java

Added:      
imaSdkSettings.setEnableOmidExperimentally(adConfig.isOMIDExperimentalEnabled());

FEM-2136 Add IMAConfig setting for supporting IMA setEnableOmidExperimentally

---

playkit/build.gradle
playkitdemo/build.gradle

remove ima dependency from build.gradle

remove ima

---

playkit/src/main/java/com/kaltura/playkit/PKPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/SamplePlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ott/PhoenixAnalyticsPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ott/TVPAPIAnalyticsPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ovp/KalturaLiveStatsPlugin.java
playkit/src/main/java/com/kaltura/playkit/plugins/ovp/KalturaStatsPlugin.java

add getVersion api

---

playkit/src/main/java/com/kaltura/playkit/PKMediaConfig.java
playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/player/MediaPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerSettings.java
playkit/src/main/java/com/kaltura/playkit/player/SourceSelector.java
playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java

PKMediaConfig mediaConfig = new PKMediaConfig()
.setMediaEntry(mediaEntry)
.setStartPosition(0)
.setPreferredMediaFormat(PKMediaFormat.hls);

FEM-1749_1 - [FEM-2146]  add API to MediaConfig to choose preferred media format

---

playkit/src/main/java/com/kaltura/playkit/player/TrackSelectionHelper.java

If format.language is null define it as Unknown.

If format.language is null define it as Unknown.

---

playkit/src/main/java/com/kaltura/playkit/player/vr/VRSettings.java

app will have to validate device supports motion before setting motion ability

FEM-2164 make interaction mode default value to touch

---

playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java

reset the player on stop so change media from dash to hls will not end with Exo Exception - Out Of Bound in get window position

FEM-2186 - reset the player on stop 

---

playkit/src/main/java/com/kaltura/playkit/Player.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/LoadControlBuffers.java
playkit/src/main/java/com/kaltura/playkit/player/PKMediaSourceConfig.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerEngineFactory.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerSettings.java

Added api to player settings
using LoadsControlBuffers Builder API
i.e
player.getSettings().setPlayerBuffers(new LoadControlBuffers().setMinPlayerBufferMS(2500).setMaxPlayerBufferMS(50000));

FEM-2204  Add Ability to Customize ExoPlayer LoadControl

---

playkit/src/main/java/com/kaltura/playkit/PKMediaConfig.java
playkit/src/main/java/com/kaltura/playkit/player/ExoPlayerWrapper.java
playkit/src/main/java/com/kaltura/playkit/player/PKMediaSourceConfig.java
playkit/src/main/java/com/kaltura/playkit/player/PlayerController.java

fix start from to support > 0 in VOD
no start from 0 in LIVE
enable start from 0 in LIVE_DVR

FEM-2212 Fix onPause onResume in DVR/LIVE + DVR Live start from
